### PR TITLE
Fixes for Evaluator Camera Type, Thermal Model Config, and Field Initialization

### PR DESCRIPTION
**Pull request by YunSeok-Kang**
This pull request addresses three key issues identified in the codebase:

1. **Evaluator Camera Type Issue**
   - Identified and fixed an issue in `evaluator.py` where `camera_ray_bundle` was of type `Camera` instead of `RayBundle`.
   - Added code to generate camera indices and convert `camera_ray_bundle` to `RayBundle` using the `generate_rays` method.

2. **ThermalNerfModelConfig Cold Flag**
   - Fixed an issue where the 'cold' attribute was missing in `ThermalNerfModelConfig`, causing an `AttributeError`.
   - Added a new boolean flag `cold` to indicate if the dataset includes cold temperatures.

3. **ThermalNerfactoTField Initialization**
   - Fixed an issue with `ThermalNerfactoTField` initialization where `average_init_density` was incorrectly set to a string value 'tcnn' instead of a numeric value.
   - Corrected the `super().__init__` call in `ThermalNerfactoTField` to include the `average_init_density` parameter correctly.

These fixes improve the stability and correctness of the codebase, ensuring proper type handling and configuration management.

### CODE REVIEW

**Comment by YunSeok-Kang** [comment]
This pull request also addresses the issue described in #5.

Issue #5 Description:
TypeError: only integer tensors of a single element can be converted to an index
Description:
I encountered the following error while running the program:
density = self.average_init_density * trunc_exp(density_before_activation.to(positions))
TypeError: only integer tensors of a single element can be converted to an index

Resolution:
The error was caused by `self.average_init_density` being incorrectly set to a string value 'tcnn' instead of a numeric value. The initialization in `ThermalNerfactoTField` has been corrected to pass the appropriate numeric value for `average_init_density`.

With this fix, the TypeError should no longer occur, and the program should run as expected.

**Comment by MalcolmMielle** [comment]
HI Sorry for the delay I only now saw this PR. I'll have a look!

Thanks for contributing!

**Review by MalcolmMielle — COMMENTED** [review]
Thanks for the PR. ThermoNeRF is based on python3.10 and as such we would prefer keeping 3.10 annotation type. Could you remove the annotations changes? Thanks for the rest of the contributions!

**Comment by YunSeok-Kang** [comment]
@MalcolmMielle Oh, I think I made a bad commit while modifying it to work on top of Python 3.9 on my local environment, sorry, I'll pull request again.

**Pull request closed without merging**
